### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by BenRussert** [nerdmax/html-webpack-change-assets-extension-plugin#75]
Will this package be updated with webpack 5 support?

As far as I can tell this is still the best way to use html-webpack-plugin if you use gzip compressed js assets, but the plugin does not work with v5+ of webpack/html-webpack-plugin.

**Comment by nerdmax** [comment]
Hi @BenRussert Sorry for the late response. Thank you for letting me know this! I'll look into it and raise an update shortly.

**Comment by nerdmax** [comment]
@BenRussert I just published the version 1.3.0 which supports html-webpack-plugin@5. Thank you again for reporting this issue!

**Comment by nerdmax** [comment]
@BenRussert I just published the version 1.3.0 which supports html-webpack-plugin@5. Thank you again for reporting this issue!
