### ISSUE TITLE
html-webpack-plugin compatibility

### ISSUE THREAD

**Issue by Pawel-Janik** [nerdmax/html-webpack-change-assets-extension-plugin#81]
Hey, I see you've introduced  _"html-webpack-plugin": "^3.2.0 || ^4.0.0 || ^5.0.0",_ as a pear dependency. Thanks for that. 

However, when I download the latest version from NPM (1.3.0) it still has the `"html-webpack-plugin": "^3.2.0 || ^4.0.0-beta.4"` peer dependency specified in package.json. 

Is there a chance for 1.3.1 version with that `peerDependencies` updated?

**Comment by nerdmax** [comment]
Ops, sorry I forgot to update the npm's package.json file. I'll update that in 1.3.1 shortly. Thank you so much for reporting this issue!

**Comment by nerdmax** [comment]
Done. I can see the peerDependencies has been updated in package.json in 1.3.1. Thx @Pawel-Janik again for reporting this issue! 👍 

<img width="348" alt="image" src="https://user-images.githubusercontent.com/18550349/193392175-11d55d84-67d1-4185-8e92-125fdbd02bcd.png">
